### ISSUE TITLE
Bug with empty sequences

### ISSUE THREAD

**Issue by alexandreczg** [uriyyo/fastapi-pagination#958]
In the case our pagination returns an empty sequence, the execution will throw:

```
Traceback (most recent call last):
  File "/workspaces/allegro-api/./allegro_api/util/routing.py", line 37, in wrapper
    return await func(*args, **kwargs)
  File "/workspaces/allegro-api/./allegro_api/routers/content.py", line 157, in get_content_entries
    return paginate(
  File "/workspaces/allegro-api/.venv/lib/python3.10/site-packages/fastapi_pagination/paginator.py", line 28, in paginate
    return create_page(
  File "/workspaces/allegro-api/.venv/lib/python3.10/site-packages/fastapi_pagination/api.py", line 180, in create_page
    return _page_val.get().create(items, **kwargs)
  File "/workspaces/allegro-api/.venv/lib/python3.10/site-packages/fastapi_pagination/default.py", line 65, in create
    pages = ceil(total / size) if total is not None else None
ZeroDivisionError: division by zero
```

This is due to line #65: 

`pages = ceil(total / size) if total is not None else None`

Full method:

```python
class Page(BasePage[T], Generic[T]):
    page: Optional[GreaterEqualOne]
    size: Optional[GreaterEqualOne]
    pages: Optional[GreaterEqualZero] = None

    __params_type__ = Params

    @classmethod
    def create(
        cls,
        items: Sequence[T],
        params: AbstractParams,
        *,
        total: Optional[int] = None,
        **kwargs: Any,
    ) -> Page[T]:
        if not isinstance(params, Params):
            raise TypeError("Page should be used with Params")

        size = params.size if params.size is not None else total
        page = params.page if params.page is not None else 1
        pages = ceil(total / size) if total is not None else None

        return create_pydantic_model(
            cls,
            total=total,
            items=items,
            page=page,
            size=size,
            pages=pages,
            **kwargs,
        )
```

There should be guardrails in place for this. 

```python
if size == 0:
   pages = 0
else:
  pages = ceil(total / size) if total is not None else None
```

**Comment by uriyyo** [comment]
Hi @alexandreczg,

New version `0.12.14` has been released, this issue should be fixed.

**Comment by alexandreczg** [comment]
Hi @uriyyo , thanks for the quick action. I'm still facing an error with empty sequences.

```
Traceback (most recent call last):
  File "/workspaces/allegro-api/./allegro_api/util/routing.py", line 37, in wrapper
    return await func(*args, **kwargs)
  File "/workspaces/allegro-api/./allegro_api/routers/v1/packages.py", line 304, in get_package_entries
    return paginate(
  File "/workspaces/allegro-api/.venv/lib/python3.10/site-packages/fastapi_pagination/paginator.py", line 28, in paginate
    return create_page(
  File "/workspaces/allegro-api/.venv/lib/python3.10/site-packages/fastapi_pagination/api.py", line 180, in create_page
    return _page_val.get().create(items, **kwargs)
  File "/workspaces/allegro-api/.venv/lib/python3.10/site-packages/fastapi_pagination/default.py", line 73, in create
    return create_pydantic_model(
  File "/workspaces/allegro-api/.venv/lib/python3.10/site-packages/fastapi_pagination/utils.py", line 151, in create_pydantic_model
    return model_cls(**kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for CustomizedPage[Package]
size
  ensure this value is greater than or equal to 1 (type=value_error.number.not_ge; limit_value=1)
```

I think the size parameter on the customized page model needs to accept sizes of 0.

**Comment by alexandreczg** [comment]
it's just the default page with optional parameters
```python
PageWithOptionalParams = Page.with_params(
    OptionalParams
)  # https://github.com/uriyyo/fastapi-pagination/discussions/542

```

**Comment by uriyyo** [comment]
Hi @whatoeat2night @alexandreczg I am planing to release the fix tomorrow.

**Comment by uriyyo** [comment]
Hi @whatoeat2night @alexandreczg

New version `0.12.15` has been released, and this issue should be fixed

**Comment by uriyyo** [comment]
@whatoeat2night @alexandreczg Any updates? Can I close this issue?

**Comment by alexandreczg** [comment]
@uriyyo I can confirm it is now working. Thank you for your dedication.

**Comment by uriyyo** [comment]
@alexandreczg Thanks for your feedback, I am closing this issue
